# Generated by Django 6.0.3 on 2026-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='pizza',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
